FROM golang:1.25-alpine

# tools we need inside the container
RUN apk add --no-cache \
  bash git curl jq openssl \
  docker-cli docker-cli-compose \
  sops \
  dbus bluez bluez-dev

WORKDIR /app

# live-reload for dev
RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

CMD ["air", "-c", ".air.toml"]
