services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/dbus:/var/run/dbus
    environment:
      ENV: "debug"
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/var/run/dbus/system_bus_socket"
    network_mode: host
    privileged: true
    container_name: machine 
    command: ["air", "-c", ".air.toml"]

  machine:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/dbus:/var/run/dbus
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/var/run/dbus/system_bus_socket"
    network_mode: host
    privileged: true
    container_name: machine-prod
